{% if values.certManagerEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesCertManager
metadata:
  name: {{ values.cluster_name }}-cert-manager
  group: security-addons
  relationships:
    - kind: AzureAksNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: AzureAksCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

