{% if values.istioEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesIstio
metadata:
  name: {{ values.cluster_name }}-istio-ingress
  group: networking-addons
  relationships:
    - kind: AzureAksNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: AzureAksCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

