{% if values.elasticOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesElasticOperator
metadata:
  name: {{ values.cluster_name }}-elastic-operator
  group: observability-operators
  relationships:
    - kind: AwsEksNodeGroup
      name: "{{ values.node_group_name }}"
      type: runs_on
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: AwsEksCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

