{% if values.ingressNginxEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesIngressNginx
metadata:
  name: {{ values.cluster_name }}-ingress-nginx
  relationships:
    - kind: AwsEksNodeGroup
      name: "{{ values.node_group_name }}"
      type: runs_on
      group: networking-addons
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: AwsEksCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

