{% if values.certManagerEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesCertManager
metadata:
  name: {{ values.cluster_name }}-cert-manager
  relationships:
    - kind: DigitalOceanKubernetesCluster
      name: "{{ values.env }}-{{ values.cluster_name }}"
      type: runs_on
      group: security-addons
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: DigitalOceanKubernetesCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

