{% if values.externalSecretsEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesExternalSecrets
metadata:
  name: {{ values.cluster_name }}-external-secrets
  relationships:
    - kind: GcpGkeNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
      group: security-addons
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

