{% if values.solrOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesSolrOperator
metadata:
  name: {{ values.cluster_name }}-solr-operator
  relationships:
    - kind: GcpGkeNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
      group: database-operators
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

