{% if values.postgresOperatorEnabled | bool %}
---
apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesZalandoPostgresOperator
metadata:
  name: {{ values.cluster_name }}-postgres-operator
  group: database-operators
  relationships:
    - kind: GcpGkeNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
spec:
  targetCluster:
    kubernetesClusterSelector:
      clusterKind: GcpGkeCluster
      clusterName: "{{ values.env }}-{{ values.cluster_name }}"
{% endif %}

